-- AlterTable
ALTER TABLE `mejora` ADD COLUMN `cantidad` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `pokemon` ADD COLUMN `indiceSlot` INTEGER NULL;

-- AlterTable
ALTER TABLE `usuario` ADD COLUMN `clicks` BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN `cps` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `tema` VARCHAR(191) NOT NULL DEFAULT 'system',
    ADD COLUMN `ultima_actualizacion` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
